digitalocean/digitalocean-cloud-controller-manager

- README.md
Adds better documentation around using --kubelet-preferred-address-types on the apiserver
https://github.com/digitalocean/digitalocean-cloud-controller-manager/issues/16
> improve docs regarding kubelet preferred addresses

- do/loadbalancers.go
- do/loadbalancers_test.go
Waits for the balancer to be `active` at Digital Ocean.
Times out if the balancer is not active within a minute
**Please**, review the timeout and timespan values (60, 5 respectively), since they are hardcoded consts.
Related to https://github.com/digitalocean/digitalocean-cloud-controller-manager/issues/22
> Wait for load balancer to be active to retrieve its IP

- README.md
> add @odacremolbap as a maintainer

- CHANGELOG.md
- Makefile
- releases/v0.1.1.yml
This will likely be the last release for v1.7.X including changes from https://github.com/digitalocean/digitalocean-cloud-controller-manager/pull/23 & https://github.com/digitalocean/digitalocean-cloud-controller-manager/pull/25
cc @odacremolbap
> release v0.1.1

- do/cloud.go
- do/droplets.go
- do/droplets_test.go
- do/zones.go
- do/zones_test.go
> implement the k8s 1.8 Zones interface

- main.go
Fixes https://github.com/digitalocean/digitalocean-cloud-controller-manager/issues/34
> remove import to in-tree cloud providers

- do/droplets.go
For https://github.com/digitalocean/digitalocean-cloud-controller-manager/issues/21.
> Implement InstanceExistsByProviderID

- Makefile
- README.md
- releases/v0.1.0.yml
- releases/v0.1.2.yml
Doc updates and release for v1.8
> Support Kubernetes v1.8

- README.md
This PR fixes some typo fixes and improves formatting.
/cc @andrewsykim
> readme: several typo fixes

- README.md
- releases/secret.yml.tmpl
- scripts/generate-secret.sh
> Use stringData for Kubernetes Secret containing DO Token

- do/droplets.go
Fix #20
---
I haven't tested this ([bad experience in the past](https://github.com/digitalocean/digitalocean-cloud-controller-manager/issues/24)), but it should work..
> Support clusters where nodeName is the private or public IP

- CHANGELOG.md
- Makefile
- releases/v0.1.3.yml
> release v0.1.3

- .travis.yml
- Makefile
- do/cloud.go
- do/droplets.go
- do/loadbalancers.go
- do/loadbalancers_test.go
* make sure `.PHONY` isn't the default target
* add golint target and fix problems identified by `golint`.
* clean up all packages and remove unnecessary build path
* add code quality checks to the `all` target
* add golint to the `ci` target
* separate `.PHONY` target dependencies
> Makefile improvements

- do/loadbalancers.go
- do/loadbalancers_test.go
> do: loadbalancer sticky sessions implementation

- CHANGELOG.md
- Makefile
- README.md
- examples/loadbalancers/http-with-sticky-sessions.yml
- releases/v0.1.4.yml
cc @xmudrii @bhcleek 
Fixes https://github.com/digitalocean/digitalocean-cloud-controller-manager/issues/44
> release v0.1.4 - support sticky sessions and add RBAC

- do/csi/cmd/do-csi-plugin/Dockerfile
- do/csi/cmd/do-csi-plugin/Makefile
- do/csi/driver/driver.go
- do/csi/driver/driver_test.go
- do/csi/driver/mounter.go
- do/csi/driver/node.go
This adds the NodeServer interface of the CSI spec. The test suite is passing and is also enabled in this PR. However there are many things todo yet and is not tested against a real K8S server.
> csi: add NodeServer interface implementation

- README.md
- do/loadbalancers.go
Add Travis build badge.
Add go report card badge.
Fix a typo.
> Add badges

- examples/loadbalancers/http-nginx-with-redirect.yml
> add example of creating LB with http -> https redirect

- Makefile
> compile binary in docker

- cloud-controller-manager/do/loadbalancers.go
- cloud-controller-manager/do/loadbalancers_test.go
- docs/controllers/services/annotations.md
- docs/controllers/services/examples/http-nginx-with-healthcheck-protocol.yml
Fixes https://github.com/digitalocean/digitalocean-cloud-controller-manager/issues/145
> support overriding load balancer health check protocol

- README.md
> add @timoreimann as a maintainer

- Gopkg.lock
> Synchronize dep manifest and lock file.

- Gopkg.toml
- cloud-controller-manager/do/cloud.go
- cloud-controller-manager/do/loadbalancers.go
- cloud-controller-manager/do/loadbalancers_test.go
- docs/controllers/services/annotations.md
- docs/controllers/services/examples/README.md
Some minor fixes to the documentation and renaming of `loadbalancers` to `loadBalancers`
> add some documentation and fix the load balancer naming

- e2e/e2e_test.go
This is to account for the case where the last test has finished, and the cluster is being torn down before CCM has had a chance to delete the DigitalOcean load-balancer.
> e2e: Check that LB has wound down for sure.

- ci/gofmt.sh
- ci/headers-bash.sh
- ci/headers-docker.sh
- ci/headers-go.sh
- e2e/e2e.sh
- e2e/scripts/cleanup-resources.sh
- e2e/scripts/destroy_cluster.sh
- e2e/scripts/install_deps.sh
- e2e/scripts/setup_cluster.sh
- e2e/scripts/utils.sh
- scripts/generate-secret.sh
> Change shebang to /usr/bin/env bash.

- cloud-controller-manager/do/resources.go
If a user has 1000+ services and 100+ load balancers this loop could get slow. Optimize it to have O(M+N) aka O(N) characteristics instead of O(MN).
Adressing https://github.com/digitalocean/digitalocean-cloud-controller-manager/pull/181/files#r260260832
> resources: Make load balancer tag syncing O(N)

- cloud-controller-manager/do/resources.go
> Unwind resource controller tag loop.

- cloud-controller-manager/do/resources_test.go
The ordering of the collected tag request resources depends on the ordering of the services which are retrieved from the informer cache. However, the informer's List() is not deterministic (under the hood, it iterates over a map).
Thus, we sort the resources prior to asserting.
> loadbalancers: deflake test for multiple tags.

- README.md
- Use dedicated section.
- Fix and extend git commands.
- Include tagging.
- Refer to `<new version>` where appropriate.
@nanzhong @fatih @bouk PTAL.
> Improve release process documentation

- docs/controllers/services/examples/http-nginx-with-redirect.yml
- docs/controllers/services/examples/https-with-cert-nginx-minimal.yml
- docs/controllers/services/examples/https-with-cert-nginx.yml
Updating the examples to use an actually UUID for clarity
> Adding UUID

- README.md
https://github.com/digitalocean/digitalocean-cloud-controller-manager/issues/220
> Add note to README about CCM being already installed on DOKS

- cloud-controller-manager/do/droplets_test.go
Add tests for droplet matching unrelated to the droplet name as provided by the `dropletByName()` function.
For test resilience reasons, we run the tests through a public method.
Refs #218.
> Add tests for droplet matching

- go.mod
This showed up after running `make ci`.
> Updated go.mod with pflags entry

- Makefile
To avoid missing go.mod updates.
> Check for unused and missing packages in go.mod + vendor

- CHANGELOG.md
- Use change log sub-sections consistently.
- Add missing items.
Spotted during #241, which needs to be rebased after this PR gets merged.
> Fix and complete change log

- docs/controllers/services/annotations.md
> Fix http2 reference in the service annotation docs

- CHANGELOG.md
This slipped into the wrong section.
> Move LB rename change log entry to "unreleased"

- docs/controllers/services/examples/README.md
The improvements came out of responses provided to customers [here](https://github.com/digitalocean/DOKS/issues/8#issuecomment-522876715).
> Improve doc section about via-LB requests

- docs/controllers/services/examples/README.md
- docs/controllers/services/examples/http-nginx-with-healthcheck-numeric-values.yml
- docs/controllers/services/examples/http-nginx-with-healthcheck-path.yml
- docs/controllers/services/examples/http-nginx-with-healthcheck-protocol.yml
- docs/controllers/services/examples/http-nginx-with-proxy-protocol.yml
- docs/controllers/services/examples/http-nginx-with-redirect.yml
- docs/controllers/services/examples/http-nginx.yml
- docs/controllers/services/examples/http-with-least-connections-nginx.yml
- docs/controllers/services/examples/http-with-sticky-sessions.yml
- docs/controllers/services/examples/http2-with-cert-nginx.yml
- docs/controllers/services/examples/http2-with-hostname-and-cert.yml
- docs/controllers/services/examples/http2-with-pass-through-nginx.yml
- docs/controllers/services/examples/http2-with-sticky-sessions.yml
- docs/controllers/services/examples/https-with-cert-nginx-minimal.yml
- docs/controllers/services/examples/https-with-cert-nginx.yml
- docs/controllers/services/examples/https-with-hostname-and-cert.yml
- docs/controllers/services/examples/https-with-pass-through-nginx.yml
- docs/controllers/services/examples/https-with-sticky-sessions.yml
- docs/controllers/services/examples/tcp-nginx.yml
Updates apiVersion for Deployments in example manifests to apps/v1
Fixes #285
> Update Deployment apiVersion to apps/v1

- docs/controllers/services/examples/README.md
This pull requests adds docs on surfacing reconciliation errors that can happen during provisioning a load balancer _via_ cloud controller manager.
> Add docs on accessing a load balancer provisioning errors

- cloud-controller-manager/do/firewall_controller.go
Getting `context deadline exceeded` errors within the Firewall Controller. Looks to be because of how we currently initialize the context in a particular part of the worker item logic.
This PR:
- updates the logic to create the context after an item is retrieved from the queue
- adds a timeout value to be used within the context that's created within the process worker item logic
- adds a better error message, relating to the fact we failed to retrieve an item from the worker queue
> Create context after retrieving item from worker queue

- CHANGELOG.md
- cloud-controller-manager/do/firewall_controller.go
This is how controllers are supposed to be used.
See also the [canonical sample controller implementation](https://github.com/kubernetes/sample-controller/blob/bc98db7fe443244690abef147d4da7bdff956476/controller.go#L185-L238).
> Do not forget work item on firewall controller error

- .github/workflows/release.yml
> ci/release: need to be logged in to push docker image

- releases/dev.yml
- uncommented the required permission and made a copy of the file and added a -dev suffix
Fixes #397
/assign @timoreimann
> uncommented the required permission

- Makefile
- README.md
- bump go to the latest release
/assign @timoreimann
> bump go to the latest release

- .github/dependabot.yml
- add dependabot to upgrade the dependencies and keep the repo up to date
/assign @timoreimann
> add dependabot to upgrade the dependencies

- Makefile
- Derive release manifest from dev one.
- Update change log date header. (Requires #450 to work.)
- Delete sed backup files.
> Improve make bump-version

- .github/workflows/test.yml
- Makefile
- releases/dev.yml
Create an updated `:dev` image every time we merge master.
> ci: publish dev image on master build

- .github/workflows/release.yml
- .github/workflows/test.yml
- Makefile
Also remove the "ci" Makefile build target from the "publish" one to avoid rerunning tests unnecessarily during CI.
> Add missing Go setup to release-dev-image

- README.md
- cloud-controller-manager/do/cloud.go
- cloud-controller-manager/do/metadata.go
- go.mod
This change addresses #511, and is needed for running the Digitalocean-CCM outside of Digitalocean.
> Change FAKE_REGION to REGION

- README.md
Fixes :- #528
all typos fixed in README.md
> Fixed all typos in README.md

- docs/controllers/services/annotations.md
annotation should be 'service.beta.kubernetes.io/do-loadbalancer-allow-rules'
> docs: minor wording fix

- cloud-controller-manager/do/lb_service_admission_handler.go
- cloud-controller-manager/do/lb_service_admission_handler_test.go
The admission webhook currently rejects updates made to a service if the updated entity doesn't already have an LB ID set. This change introduces a better validation logic that:
- Validates the service as a new load-balancer against the godo API when the updated service doesn't have an LB ID before or after the update.
- Prefers the updated LB ID over the previously set one.
> fix(admission-webhook): better validation logic for LB creation/updates

- cloud-controller-manager/do/loadbalancers.go
- cloud-controller-manager/do/loadbalancers_test.go
Traffic will land on the worker node destined for the port of the service and not the node port. If there is an LB with port:80 and targetPort:8000. Then traffic will be configured to flow through the NLB on port: 80, will be forwarded to a DOKS worker node with DST IP=VIP and DST port=80, and then kube-proxy/cillium will take care of routing it to an appropriate pod.
> Update forwarding rule logic for REGIONAL_NETWORK

- CHANGELOG.md
Needed for our automatic release job to properly insert the current date.
> Adjust changelog

- docs/cloud-controller-manager.md
> Fix links to Service and Node examples

- CHANGELOG.md
> CON-11819 Prepare CHANGELOG for v0.1.59
