do/common.go, do/droplets.go, do/loadbalancers.go, do/loadbalancers_test.go
When the droplet count in the digital ocean account exceeds the size of one api result page, dropletByName, and nodesToDropletIDs were not able to match the droplet to the node.
=> Fix LoadBlancer And Instances, when do droplet count exceeds one page

do/droplets_test.go, do/zones.go, do/zones_test.go
Use the region slug instead of the region name to communicate the region
of a given node.
=> use the region slug instead of region name

do/droplets.go, do/droplets_test.go, do/zones.go, do/zones_test.go
Addresses https://github.com/digitalocean/digitalocean-cloud-controller-manager/issues/15. 
In v1.7.x this wasn't important since CCM never set providerID in the first place. In v1.8, it will so we should handle the expected format. The expected format for node's providerID is `digitalocean://droplet-id`, example:
```yaml
apiVersion: v1
kind: Node
metadata:
annotations:
node.alpha.kubernetes.io/ttl: "0"
volumes.kubernetes.io/controller-managed-attach-detach: "true"
creationTimestamp: 2017-09-27T14:30:44Z
labels:
beta.kubernetes.io/arch: amd64
beta.kubernetes.io/instance-type: 512mb
beta.kubernetes.io/os: linux
kubernetes.io/hostname: k8s-worker-01
kubernetes.io/role: node
name: k8s-worker-01
resourceVersion: "7123"
selfLink: /api/v1/nodes/k8s-worker-01
uid: …
```
=> Handle correct providerID format

releases/v0.1.0.yml, releases/v0.1.1.yml
Fixes https://github.com/digitalocean/digitalocean-cloud-controller-manager/issues/32. Also adds toleration for master node taint.
@odacremolbap as you mentioned, 100m CPU and 50Mi memory seems pretty reasonable for now. It's also a resource request and not a limit for now so it can still burst if needed. 
In general, I think we should avoid making changes to the files in releases as they should be locked down once a release goes in. But this change seems pretty harmless since we're not changing any of the CCM flags that might change its behavior.
=> CCM should be critical pod and have resource requests

README.md
This PR fixes the link for `cloud-provider-refactoring` document.
=> readme: fix cloud-provider-refactoring link

.gitignore, README.md, scripts/generate-secret.sh
We create a secret containing a DO access token for cloud-controller-manager to consume. Though it's documented how to create the secret, figured it would also help to create a script to make this easier. 
@xmudrii @bhcleek  r?
=> Add script to generate Kubernetes Secret for DigitalOcean

README.md, releases/.gitignore, releases/secret.yml.tmpl
* Rename releases/token.yml to releases/secret.yml.tmpl
* Add a .gitignore entry for releases/secret.yml
* Edit README.md instructions to direct users to copy
releases/secret.yml.tmpl to releases/secret.yml before replacing the
placeholder.
Edit references to DigitalOcean in README.md to be capitalized
correctly.
Edit the placeholder value; remove the the wrapping angle brackets so
that users don't mistakenly think the angle brackets are necessary.
=> reduce risk of a contributor commiting their token

do/droplets.go, do/droplets_test.go, do/loadbalancers.go, do/loadbalancers_test.go, do/metadata.go, do/zones.go
Edit godoc comments that were merely copies of Kubernetes' cloudprovider
interface definitions' godoc comments so that they describe the
behavior, expected inputs, and return values of the DigitalOcean
interface implementations of those interfaces.
Add punctuation to godoc comments where it was missing.
Replace comments documenting that do/instances and do/loadbalancers
implement cloudprovider.Instances and cloudprovider.LoadBalancers,
respectively, with variable declarations in test files that verify the
same.
Rename a couple of method parameters to be cased in the standard fashion
(e.g. providerId -> providerID).
=> edit godoc

README.md, releases/secret.yml.tmpl, scripts/generate-secret.sh
This PR adds `-w 0` flag to the all base64 to prevent confusion as `base64` automatically adds new line after 72 characters.
This also fix the secret generation script, as it returns the following error if new line is present:
```
...
Create the following secret to your default kubectl context? [y/N]: y
Creating Kubernetes Secret for DigitalOcean
error: error converting YAML to JSON: yaml: line 9: could not find expected ':'
```
/cc @andrewsykim
=> docs: account for new lines in base64 encoded secrets

Dockerfile, Makefile
This reduce the image size by 75%.
Before this change the image size was 214MB, now it is only 50.2MB.
---
Note: Not tested..
=> Switch Docker base image to Alpine from Ubuntu

.travis.yml
Needs quoting because of how YAML interprets the value, see: https://twitter.com/dgryski/status/964626204488695808
=> travis: use new Go version

do/common.go, do/droplets.go, do/loadbalancers.go
=>  loadbalancers: Support nodes where nodeName is the private or public IP 

Gopkg.lock, Gopkg.toml, vendor/k8s.io/apiextensions-apiserver/BUILD, vendor/k8s.io/apiextensions-apiserver/README.md, vendor/k8s.io/apiextensions-apiserver/pkg/features/BUILD, vendor/k8s.io/client-go/pkg/version/base.go
k8s.io/apiextensions-apiserver and k8s.io/client-go are transitive
dependencies, not direct dependencies, so need to be in the overrides
instead of the constraints.
After moving them and running dep ensure,the apiextensions-apiserver was
properly updated (it must have previously been vendored from the
kubernetes-1.8.1 tag that last time I upgraded k8s.io packages).
=> move apiextensions-apiserver and client-go to overrides

do/loadbalancers.go, do/loadbalancers_test.go
Add the option to specify redirect_http_to_https on the DO load balancer resource using the annotation
```
service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https
```
As per the specification at https://developers.digitalocean.com/documentation/v2/#load-balancers this defaults to false.
=> [load_balancer] add annotation for redirect_http_to_https option

do/droplets.go, do/droplets_test.go
fixes https://github.com/digitalocean/digitalocean-cloud-controller-manager/issues/94 
Adds taints to node if it is shutdown
other refs: https://github.com/kubernetes/kubernetes/issues/58635
=> Implement InstanceShutdownByProviderID

README.md
Going forward we should have a known and strict policy about versioning
and set the expectations accordingly. This PR adds the related
information.
Note that I also changed which supports are officially supported by us.
This means replying to issues and handling bug fixes. We should not
maintain older versions or very new versions unless we also support it
on DigitalOcean Kubernetes. Currently we don't have the time and
manpower to support fully all Kubernetes versions.
=> README: add versioning process and support level

README.md
Looks like the links to these docs were broken when the docs were shuffled around.
cc @andrewsykim
=> Fix incorrect links to examples

.travis.yml
golint [introduced an import path check](https://github.com/golang/lint/commit/9a272034dedb2a3ed05231d5604ce17fb40f0e58) recently.
Updating to the new path re-enables golint.
=> Update golint import path to please the import path checker.

cloud-controller-manager/do/cloud.go
Also omit the function variable name in `RegisterCloudProvider` to indicate that we do not use it.
=> Drop unused io.Reader function variable to newCloud.

cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go
Addresses the following golint complaints:
```
/go/src/github.com/digitalocean/digitalocean-cloud-controller-manager/cloud-controller-manager/do/loadbalancers.go:81:2: const annDORedirectHttpToHttps should be annDORedirectHTTPToHTTPS
/go/src/github.com/digitalocean/digitalocean-cloud-controller-manager/cloud-controller-manager/do/loadbalancers.go:315:2: var redirectHttpToHttps should be redirectHTTPToHTTPS
/go/src/github.com/digitalocean/digitalocean-cloud-controller-manager/cloud-controller-manager/do/loadbalancers.go:590:6: func getRedirectHttpToHttps should be getRedirectHTTPToHTTPS
/go/src/github.com/digitalocean/digitalocean-cloud-controller-manager/cloud-controller-manager/do/loadbalancers.go:591:2: var redirectHttpToHttps should be redirectHTTPToHTTPS …
```
=> Rename http/s variable fragments to HTTP/S.

README.md
It is prone to changes. Additionally, maintainers are best accessed differently (e.g., through the [contributors page](https://github.com/digitalocean/digitalocean-cloud-controller-manager/graphs/contributors) or by letting maintainers respond to community activities on their own).
Follow-up of #155.
=> Remove maintainers section.

e2e/README.md, e2e/scripts/cleanup-resources.sh
This can become handy when the end-to-end tests fail to tear down resources.
=> Add script to clean up used DigitalOcean resources.

Gopkg.lock, Gopkg.toml, cloud-controller-manager/do/cloud.go, cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go, vendor/github.com/digitalocean/godo/account.go, vendor/github.com/digitalocean/godo/cdn.go, vendor/github.com/digitalocean/godo/domains.go, vendor/github.com/digitalocean/godo/droplets.go, vendor/github.com/digitalocean/godo/firewalls.go, vendor/github.com/digitalocean/godo/floating_ips.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/images.go, vendor/github.com/digitalocean/godo/kubernetes.go, vendor/github.com/digitalocean/godo/load_balancers.go, vendor/github.com/digitalocean/godo/projects.go, vendor/github.com/digitalocean/godo/storage.go, vendor/github.com/digitalocean/godo/strings.go, vendor/github.com/digitalocean/godo/tags.go
This enables a consistent view on all DO resources managed by the cluster.
As a drive-by change, some struct initializations were changed to use named fields in order to be more robust towards (optional) field additions in the future.
digitalocean/godo had to be updated in order to access load balancer tags.
=> Tag created load balancers with existing cluster ID.

cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go
Addresses an oversight spotted by @bouk [here](https://github.com/digitalocean/digitalocean-cloud-controller-manager/pull/170#pullrequestreview-205834323).
=> Prepend the DO-specific tag component to the cluster ID.

Makefile, cloud-controller-manager/cmd/digitalocean-cloud-controller-manager/Dockerfile, cloud-controller-manager/do/zones_test.go
The target would previously not work (because the wildcard in the command did not apply).
=> Makefile: Fix check-headers target and header violations.

cloud-controller-manager/do/faketagssvc_test.go, cloud-controller-manager/do/resources.go, cloud-controller-manager/do/resources_test.go
`loadBalancers[lb.Name] = &lb` was getting a pointer to the loop variable, not to the value inside the slice (tricky Go escape semantics...). This meant that every value in the map would point to the same value, which would be the load balancer returned last from the API. So if there were multiple load balancers only the last one would get the cluster tag applied.
I changed it to have the IDs in the map instead of the load balancer pointers. I also added a test that actually verifies that the correct API requests are made.
=> loadbalancers: don't use pointer to loop variable in load balancers map

CHANGELOG.md, cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go, docs/controllers/services/annotations.md, docs/controllers/services/examples/http-nginx-with-healthcheck-numeric-values.yml
The existing, default parameters slightly vary from the defaults that DO LB provides. In order to avoid introducing behavioral changes, we kept them accordingly.
Details:
- Add and parse new annotations.
- Refactor and extend tests.
- Extend service annotation documentation.
- Add example.
- Update change log.
=> Add support for customizing remaining, numeric health check parameters

CHANGELOG.md, Gopkg.lock, Gopkg.toml, cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go, docs/controllers/services/annotations.md, docs/controllers/services/examples/http-nginx-with-proxy-protocol.yml, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/load_balancers.go, vendor/github.com/digitalocean/godo/storage.go
Adds a new annotation `service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol` to
toggle PROXY protocol usage on and off.
=> Add support for PROXY protocol

Makefile
This should hopefully prevent version bumpers from forgetting to commit the added set of release files (like I did before and fixed after the fact through fa31e15498fd2ca7fea0ccabe82573475274518d).
=> Makefile: git add -N new release files on version bump.

Makefile
This can be helpful for testing, e.g., when pushing pre-release versions to `<personal org>/digitalocean-cloud-controller-manager`.
=> Allow to publish to Docker organizations other than DO's

cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go, docs/controllers/services/annotations.md, docs/controllers/services/examples/https-with-cert-nginx-minimal.yml
Previously, TLS options (such as the certificate ID or pass-through) would be ignored silently if either an HTTP* protocol or TLS port annotation was missing. With this change, we automatically enable the
HTTPS protocol on services exposing the default TLS port 443.
Effectively, this means that users may now omit the TLS port and protocol annotations for common use cases.
Fixes #192
@nanzhong @bouk @jcodybaker PTAL
=> Assume HTTPS protocol on default TLS port when TLS option is given.

Gopkg.lock, Gopkg.toml, cloud-controller-manager/do/cloud.go, cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go, cloud-controller-manager/do/resources.go, cloud-controller-manager/do/resources_test.go, docs/getting-started.md, vendor/github.com/digitalocean/godo/databases.go, vendor/github.com/digitalocean/godo/doc.go, vendor/github.com/digitalocean/godo/droplets.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/kubernetes.go, vendor/github.com/digitalocean/godo/load_balancers.go, vendor/github.com/digitalocean/godo/vpcs.go
With the upcoming support for multiple vpcs per region on DigitalOcean, this pr adds support to CCM for specifying a specific vpc id via env var.
=> Add support for specifying the vpc that the cluster belongs to

cloud-controller-manager/do/cloud.go, cloud-controller-manager/do/droplets.go, cloud-controller-manager/do/loadbalancers_test.go, cloud-controller-manager/do/resources.go, cloud-controller-manager/do/resources_test.go
There is a race condition that can happen at the moment when a stale resource cache for droplets can cause nodes to be deleted. The race happens when the cache for droplets is missing an actual droplet that was created since the last sync and the node controller tries to check for the existence of that node.
This PR moves the logic for update droplets and lbs into the resources struct, and introduces a `SyncDroplet` method that ensure that a droplet, given by id, is up to date in the cache. When the existence check is run, we first ensure that the droplet is up to date in the cache, before looking for its existence.
There is still a window here where a race is possible (sync run started before `SyncDroplet` is called, but doesn't finish until after `SyncDroplet` is complete and before …
=> Fix stale cache node deletion

Makefile, cloud-controller-manager/do/cloud.go
Currently, requests made by digitalocean-cloud-controller-manager send `godo/$godoVersion` as their user agent. This change updates the user agent to use the format `digitalocean-cloud-controller-manager/$ccmVersion godo/$godoVersion` in order to help us better understand `godo` usage.
=> Set a custom user agent for the godo client.

CHANGELOG.md, cloud-controller-manager/cmd/digitalocean-cloud-controller-manager/main.go, cloud-controller-manager/do/cloud.go, cloud-controller-manager/do/droplets.go, docs/example-manifests/cloud-controller-manager.yml, docs/getting-started.md
Set flags for which we know the values when configuring the Cobra run command. This allows us to drop parameters from the manifest which are highly unlikely to have any other value (though overriding via the CLI is still possible).
Probably a better way to tune the set parameters is to modify them on the `CloudControllerManagerOptions` variable which is used internally by `NewCloudControllerManagerCommand()` that we invoke. However, that latter command comes with a fair amount of flags boilerplate scaffolding that we would need to copy if we wanted to set options directly. We should rather submit a PR upstream to make configuration more flexible and less coarse-grained (i.e., not require to visit and update otherwise opaque flags).
Fixes #217
=> Set static flags in-code

Makefile
This was causing `make ci` to fail when not working from a GOPATH.
=> Remove GO111MODULE export in Makefile

cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go, cloud-controller-manager/do/resources.go, cloud-controller-manager/do/resources_test.go
`EnsureLoadBalancerDeleted` was defective in two aspects:
1. The happy path returned an error even when the delete operation succeeded. While this would fix itself eventually as the cloud provider service controller put the Service object back into its work
queue and succeed on a subsequent retry once our internal load-balancer cache synchronized with the DO API, the bug leads to one or more warning events being emitted and extra delays.
1. The load-balancer cache was not updated to remove the deleted load-balancer. This is not a problem in the general case but becomes one if users tried to re-enable the load-balancer again before the cache was able to synchronize. (At this point, `EnsureLoadBalancer` would attempt to update a non-existing load-balancer.)
This change fixes both problems. …
=> Fix EnsureLoadBalancerDeleted for happy path and cache consistency

docs/controllers/services/annotations.md, docs/controllers/services/examples/http-with-sticky-sessions.yml, docs/controllers/services/examples/https-with-sticky-sessions.yml
Add notes indicating:
- Sticky sessions will route consistently to the same nodes, not pods, so you should avoid having more than one pod per node serving requests.
- Sticky sessions require your Service to configure `externalTrafficPolicy: Local` to avoid NAT confusion on the way in.
=> Add sticky session annotation note about externalTrafficPolicy Local and max one pod per node

cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go, docs/controllers/services/annotations.md, docs/controllers/services/examples/http-with-sticky-sessions.yml
This PR updates `buildForwardingRules` to default to protocol `http` if sticky sessions enabled and `tcp` (or no protocol) is set. Otherwise this can be pretty confusing for the user if they don't explicitly define the protocol via annotation.
=> Default to HTTP for sticky sessions if no protocol is defined

cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go
Breaks `buildForwardingRules` up with `buildForwardingRule` and `buildTLSForwardingRule`.
Second of 2 PRs to be extracted from https://github.com/digitalocean/digitalocean-cloud-controller-manager/pull/231
=> Clean up LB buildForwardingRules a bit

cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go, docs/controllers/services/annotations.md
Default health check protocol to TCP if not specified, since DO LBs support only TCP or HTTP for these anyway. https://developers.digitalocean.com/documentation/v2/#load-balancers
First of 2 PRs to be extracted from https://github.com/digitalocean/digitalocean-cloud-controller-manager/pull/231
=> Default health check protocol to TCP if not specified

CHANGELOG.md, cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go, docs/controllers/services/annotations.md, docs/controllers/services/examples/http2-with-cert-nginx.yml, docs/controllers/services/examples/http2-with-pass-through-nginx.yml, docs/controllers/services/examples/http2-with-sticky-sessions.yml
Currently pushed to `snormore/digitalocean-cloud-controller-manager:dev` if you want to try it out.
~Rebased on top of https://github.com/digitalocean/digitalocean-cloud-controller-manager/pull/236 and includes changes from https://github.com/digitalocean/digitalocean-cloud-controller-manager/pull/235 and https://github.com/digitalocean/digitalocean-cloud-controller-manager/pull/234 until they're merged.~
~Rebased on top of https://github.com/digitalocean/digitalocean-cloud-controller-manager/pull/235.~
```
kind: Service
apiVersion: v1
metadata:
name: hello
annotations:
service.beta.kubernetes.io/do-loadbalancer-certificate-id: "my-cert-uuid"
service.beta.kubernetes.io/do-loadbalancer-protocol: "http2"
spec:
type: LoadBalancer
selector:
app: hello
ports:
- name: http
protocol: TCP
port: …
```
=> Add HTTP/2 support for LBs

Makefile, README.md
Following suit with https://github.com/digitalocean/csi-digitalocean/pull/147
```
$ make bump-version
make: sembump: Command not found
go: finding github.com/jessfraz/junk/sembump latest
go: finding github.com/jessfraz/junk latest
go: downloading github.com/jessfraz/junk v0.0.0-20190525220952-288569a5afad
go: extracting github.com/jessfraz/junk v0.0.0-20190525220952-288569a5afad
-> unzip /Users/snormore/go/pkg/mod/cache/download/github.com/jessfraz/junk/@v/v0.0.0-20190525220952-288569a5afad.zip: case-insensitive file name collision: "md2pdf/VERSION" and "md2pdf/version"
go get github.com/jessfraz/junk/sembump: unzip /Users/snormore/go/pkg/mod/cache/download/github.com/jessfraz/junk/@v/v0.0.0-20190525220952-288569a5afad.zip: case-insensitive file name collision: "md2pdf/VERSION" and …
```
=> bump-version: remove sembump

docs/controllers/services/annotations.md, docs/controllers/services/examples/http2-with-cert-nginx.yml, docs/controllers/services/examples/http2-with-pass-through-nginx.yml, docs/controllers/services/examples/http2-with-sticky-sessions.yml
- Move all TLS port-related semantics to the TLS port section.
- Move notes around TLS ports and protocols from the health check path section to the correct ones.
- Mention HTTP/2 in the TLS port section.
- Use name "http2" for example ports that use HTTP/2.
=> Improve documentation and examples around HTTPS, HTTP/2, and TLS usage

CHANGELOG.md, cloud-controller-manager/do/cloud.go, cloud-controller-manager/do/common.go, cloud-controller-manager/do/droplets.go, cloud-controller-manager/do/droplets_test.go, cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go, cloud-controller-manager/do/patch.go, cloud-controller-manager/do/patch_test.go, cloud-controller-manager/do/resources.go, cloud-controller-manager/do/resources_test.go, cloud-controller-manager/do/zones.go, cloud-controller-manager/do/zones_test.go, docs/getting-started.md, vendor/modules.txt
This change decouples load-balancer names from their identity, thereby permitting renames that do not impact associations to Services any longer.
Instead of the load-balancer name, we use the immutable load-balancer UUID. As a beneficial side-effect, we can eliminate the local load-balancer cache since the DigitalOcean API allows for direct lookups by UUID in O(1) (vs. O(n) that we previously experienced when iterating through all load-balancers existing in a given account).
Load-balancer IDs are added to their corresponding Service objects as annotations. This happens both on load-balancer creates as well as most retrieval operations (e.g., `EnsureLoadBalancer`) in order to annotate pre-existing Services as well. When no load-balancer ID can be found, we fall back to doing lookups by …
=> Annotate Service with LB ID and use for lookup

docs/example-manifests/cloud-controller-manager.yml, docs/getting-started.md
It was decided a fair time ago that volumes integration is to be handled by CSI. As such, we can reduce the RBAC rules and remove references from the documentation about volumes.
=> Remove RBAC rules for persistent volumes

cloud-controller-manager/do/common_test.go, cloud-controller-manager/do/droplets_test.go, cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go, cloud-controller-manager/do/resources_test.go, cloud-controller-manager/do/zones_test.go
Removes the extra godo client that was maintained on the `loadBalancers` struct; we already maintain one on the shared resources variable.
Additionally, create fake clients more consistently through factory functions that return bare `godo.Client` structs with the relevant APIs stubbed out. This prevents accidentally calling the real DO API.
=> Clean up godo client usage in prod and test code

CHANGELOG.md, cloud-controller-manager/do/common.go, cloud-controller-manager/do/droplets.go, cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go, cloud-controller-manager/do/resources.go, cloud-controller-manager/do/resources_test.go, docs/getting-started.md
Node objects may contain a provider ID of the kind `digitalocean://<droplet ID>`. At times when we need to specify the set of target droplets for load-balancer creates and updates, we now check
for the availablity of provider IDs and use them directly without relying on the local droplets cache.
This change renders the droplets cache obsolete: it was originally introduced to better support accounts with a large number of droplets. For such cases, the provider ID should be injected through the kubelet directly. Consequently, we drop the cache and resort to listing all droplets from the API only when nodes do not come with a provider ID, which should be acceptable for smaller accounts.
=> Use provider IDs for setting LB droplet targets

cloud-controller-manager/do/droplets.go, cloud-controller-manager/do/droplets_test.go
This change simplifies the existing `dropletIDFromProviderID` implementation.
It comes with two commits for comparison purposes: one to demonstrate using `net/url`, and another based on prefix matching / truncating. Overall, I don't think we need `net/url`, the custom parser seems much more straight forward and robust.
=> Simplify dropletIDFromProviderID implementation

e2e/.dockerignore, e2e/.env.sample, e2e/.gitignore, e2e/Dockerfile, e2e/README.md, e2e/docker.sh, e2e/e2e.sh, e2e/e2e_test.go, e2e/scripts/setup_cluster.sh
Noticed a couple things that were off in the e2e instructions, and also wanted an isolated way to run this in a Docker image.
=> Fix e2e instructions and add a Docker runner for them

CHANGELOG.md, cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go, docs/controllers/services/annotations.md, docs/controllers/services/examples/http2-with-cert-nginx.yml, docs/controllers/services/examples/http2-with-pass-through-nginx.yml, docs/controllers/services/examples/http2-with-sticky-sessions.yml, docs/controllers/services/examples/https-with-sticky-sessions.yml
The new annotation enables to run all protocols concurrently by allowing to specify HTTP* ports independently while maintaining backwards compatibility with the existing logic. In particular, port 443 continues to default to HTTPS unless it is explicitly bound to HTTPS.
We also add a guard preventing conflicting port sharing across both the HTTPS and HTTP2 protocols.
Fixes #254
=> Support custom annotation to specify HTTP2 ports

e2e/e2e_test.go
Our end-to-end test cleans up after itself, which includes any created services to make sure external LBs are deleted as well. To verify that the delete has properly completed, we try to send requests over the LB until it starts to return errors (which means the LB must be gone).
It is okay to skip this step if no load balancer IP was able received.
=> e2e: Do not poll winding down LB if it was never created

README.md
This adds a warning to the README file about the implications of LBs changed manually and outside of the cluster.
Addresses https://github.com/digitalocean/digitalocean-cloud-controller-manager/issues/239#issuecomment-516824411
=> Add warning about LB ownership

CHANGELOG.md, cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go
Following up on https://github.com/digitalocean/digitalocean-cloud-controller-manager/pull/260
In the v0.1.16 release we changed the behaviour slightly around how we set the health check protocol default if not specified explicitly. Previously we would use the service protocol as the default. Currently we default to TCP if not specified explicitly. This breaks the case where a health check path is specified but no health check protocol, because now we get an error back from the DO LB API of `health check path isn't available for TCP`. This PR updates the behaviour so that if a health check path is specified, but no health check protocol, then default to HTTP as the health check protocol.
=> Default to health check protocol http if health check path is specified

CHANGELOG.md, cloud-controller-manager/do/loadbalancers.go, docs/controllers/services/annotations.md, docs/controllers/services/examples/README.md, docs/controllers/services/examples/http2-with-hostname-and-cert.yml, docs/controllers/services/examples/https-with-hostname-and-cert.yml
Annotation for specifying the hostname used for the LB `status.Hostname` instead of assigning `status.IP`. This can be used to avoid this [iptables rule being written by kube-proxy](https://github.com/kubernetes/kubernetes/blob/release-1.15/pkg/proxy/iptables/proxier.go#L958-L979) for the IP. This is useful when using SSL or proxy protocol on the LB, which will break if the request doesn't goes through it, but instead is routed directly in-cluster.
1. Deploy the manifest below.
1. Wait for the service external IP to be available.
1. Add a DNS record for your hostname
1. Uncomment the hostname annotation in the manifest below. Deploy it.
```yaml
kind: Service
apiVersion: v1
metadata:
name: hello
annotations:
service.beta.kubernetes.io/do-loadbalancer-certificate-id: "1234-5678-9012-3456" …
```
=> Support LB with status.Hostname instead of status.IP

cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go, docs/controllers/services/annotations.md, docs/controllers/services/examples/http-with-sticky-sessions.yml
This PR reverts https://github.com/digitalocean/digitalocean-cloud-controller-manager/pull/234 and adds a warning/note about using sticky sessions with only a TCP forwarding rule and how it will not work as expected.
=> Do not force HTTP with sticky-sessions

cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/resources_test.go
Needed to prevent in panic when the service has no annotations whatsoever, which is the default state of annotation-less services.
Also update test service builder to leave annotations uninitialized by default in order to match the production state.
Follow-up of #245 that was discovered during end-to-end test execution.
=> Ensure annotation map exists prior to adding LB ID

CHANGELOG.md, cloud-controller-manager/do/resources.go, cloud-controller-manager/do/resources_test.go
This change reduces the times we need to talk to the DO API with regards to LB tag synchronization. Specifically, we do so in two ways:
- by increasing the synchronization interval from 1 minute to 15 minutes: previously, a lower interval was chosen to populate the local LB cache, which is not necessary anymore now that the cache has been dropped in #245.
- by checking if we have any `LoadBalancer`-typed services and skipping reaching out to the LB API endpoint if we do not.
Additional changes:
- Remove obsolete interval/timeout constants.
- Update test to explicitly return an error from the fake LB service in case where we do not expect it to be called.
=> Reduce API interactions around LB tag synchronization

CHANGELOG.md, cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go
This change causes the service load-balancer ID annotation to be overwritten if it does not match the given load-balancer ID.
It is required to properly handle the case where the load-balancer is deleted manually: in that case, CCM won't be able to look up the load-balancer and create a new one. Without updating the ID, however, subsequent reconciliations will continue to use the old ID, fail to find one, try to create a new but fail because a load-balancer with the given name (based on the service UUID) already exists. At this point, the reconciliation attempt will loop endlessly.
We need to break the cycle by annotating the ID of the newly created load-balancer.
=> Overwrite service load-balancer ID on mismatch

cloud-controller-manager/do/certificates.go, cloud-controller-manager/do/certificates_test.go, cloud-controller-manager/do/common_test.go, cloud-controller-manager/do/droplets_test.go, cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go, cloud-controller-manager/do/resources_test.go, vendor/modules.txt
While DOKS does not officially support Let's Encrypt, it is possible for users to create a DO Let's Encrypt certificate and use that cert UUID for the "service.beta.kubernetes.io/do-loadbalancer-certificate-id" on Services they create in their cluster.
This is problematic because some combination of the Certificates Service and LBaaS will automatically rotate Let's Encrypt certificates which deletes the old Certificate (resulting an invalid UUID on the "service.beta.kubernetes.io/do-loadbalancer-certificate-id" Service annotation) then updates the Loadbalancer to point at a new certificate with CCM none the wiser.
Because of the following facts:
* CCM doesn't "know" about Let's Encrypt certificates
* CCM always attempts to set the cert UUID from the Service on the LoadBalancer when making …
=> Gracefully handle DO lets_encrypt cert rotation

cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go
This helps to better identify what part of the forwarding rule building has failed.
=> Annote TLS part(s) of building forwarding rules

docs/controllers/services/annotations.md
A [kubernetes bug](https://github.com/kubernetes/kubernetes/issues/59113) caused my external-dns annotation to vanish because I had used a wrong DO service annotation with a boolean value instead of a string by accident. The load balancer annotation documentation suggests using boolean values would work here, my IDE didn't print a warning either, and using any boolean annotation causes **all** annotations on the Service object to vanish on `kubectl apply`.
This PR improves docs so other devs hopefully don't use boolean values in service annotations, possibly saving them some hours of debugging when getting bitten by similar bugs.
=> Warn about a bug in service annotations docs

CHANGELOG.md, cloud-controller-manager/cmd/digitalocean-cloud-controller-manager/main.go, cloud-controller-manager/do/cloud.go, cloud-controller-manager/do/health.go, cloud-controller-manager/do/health_test.go, go.sum
We want to expose a health check endpoint that we can use for monitoring the availability of CCM running in a cluster.
The way DO's CCM is currently implemented, it's configuring a healthz handler against the default serve mux, but actually not serving it anymore.
We re-use the upstream ccm cobra command for starting up CCM, and that [cobra command actually sets up all the health checking on the secure/unsecure bind address that you can configure with the `--address` flag](https://github.com/kubernetes/kubernetes/blob/master/cmd/cloud-controller-manager/app/controllermanager.go#L145-L169), however, due to the way that is implemented, there is no way we can access and and extend it.
Digging through what health checks it actually configures, it seems like it either installs the leader …
=> Add DO specific health check

releases/v0.1.21.yml
This somehow got lost during the latest release.
We also bump the API version to `apps/v1`.
Fixes #296
=> Add missing v0.1.21 release manifest

releases/v0.1.21.yml
Deployment in apps/v1 requires a selector to be present in the deployment spec. Otherwise applying this manifest fails with:
```
error validating data: ValidationError(Deployment.spec): missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec
```
=> Fixes v0.1.21.yml manifest to be compatible with apps/v1

cloud-controller-manager/do/cloud.go, docs/getting-started.md
- Only start the debug server if the `DEBUG_ADDR` environment variable is   specified, ensuring that existing users won't be surprised by the new functionality.
- Shut down the HTTP server gracefully, and log if it fails to do so.
- Add documentation.
=> Improve debug HTTP server usage

CHANGELOG.md, cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go
This fixes a bug where the default protocol set through the corresponding annotation would be overwritten when a secure port (i.e., an HTTPS or HTTP2 port) was discovered.
=> Maintain default protocol when secure protocol override is applied

CHANGELOG.md, cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go, docs/controllers/services/annotations.md, docs/controllers/services/examples/http-nginx-with-healthcheck-port.yml
**DO NOT MERGE**
> Need to run some integration tests to verify functionality still
* Adds `service.beta.kubernetes.io/do-loadbalancer-healthcheck-port` annotation for services to specify which port to use for the loadbalancer health check.
* Defaults to existing functionality of choosing the first port in a service
=> Add support for configurable health-check via annotation

CHANGELOG.md, README.md, cloud-controller-manager/do/metadata.go
The sole purpose of this change is to enable local testing since CCM depends on the DigitalOcean metadata service to be available, which only exists on droplets.
=> Support specifying a fake region by environment variable

README.md
This pull requests extends development docs in `README.md`.
It adds missing information about `DO_ACCESS_TOKEN` being required to run CCM locally against an external cluster.
=> Extend development docs on local testing

CHANGELOG.md, cloud-controller-manager/do/loadbalancers.go
**This PR adds logs, containing:**
* LB operation type
* configuration info from the LB request
**To test this:**
* I created a cluster using the cloud UI
* downloaded the cluster config file
* then ran the following in my local terminal:
```
cd cloud-controller-manager/cmd/digitalocean-cloud-controller-manager && FAKE_REGION=fra1 go run main.go --kubeconfig ../../../k8s-kubeconfig.yaml --leader-elect=false --v=5 --cloud-provider=digitalocean
```
This is some output for a `CREATE` operation:
```
Operation type: CREATE, Configuration info: godo.LoadBalancerRequest{Name:"a02c49ab3476b493185d7794208a3a45", Algorithm:"round_robin", Region:"fra1", ForwardingRules:[godo.ForwardingRule{EntryProtocol:"http", EntryPort:80, TargetProtocol:"http", TargetPort:32761, CertificateID:"", …
```
=> Log data when erroring on creating or updating an LB

CHANGELOG.md, cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go
We also use the opportunity to make the error message more readable for invalid health check and payload protocol.
=> Use correct annotation name for invalid health check protocol

CHANGELOG.md, cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go, docs/controllers/services/annotations.md, docs/controllers/services/examples/all-protos-nginx.yml
This facilitates concurrent use of all protocols that we support, specifically TCP, HTTP, and at least another secure protocol, by setting the default protocol to TCP and specifying the HTTP* ports through the respective annotations explicitly.
This would not be possible before since we only provided annotations to enforce the HTTPS and HTTP2 protocol on given ports, forcing users to choose between TCP or HTTP through the default protocol annotation without any means to select both for different ports.
Fixes #316
=> Add annotation to specify HTTP ports explicitly

docs/controllers/services/annotations.md
In particular, point out that it is not a NodePort that can be referenced.
=> docs: clarify that healthcheck port annotation refers to a service port

CHANGELOG.md, cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go
HTTPS was previously not supported as health check protocol [but is as of 8 July, 2020](https://www.digitalocean.com/docs/networking/load-balancers/#8-july-2020).
Fixes #335
=> Support HTTPS as health check protocol

CHANGELOG.md, cloud-controller-manager/do/certificates_test.go, cloud-controller-manager/do/cloud.go, cloud-controller-manager/do/common.go, cloud-controller-manager/do/firewall_controller.go, cloud-controller-manager/do/firewall_controller_test.go, cloud-controller-manager/do/loadbalancers_test.go, cloud-controller-manager/do/resources.go, cloud-controller-manager/do/resources_test.go, docs/getting-started.md, go.mod, go.sum, vendor/github.com/google/go-cmp/cmp/compare.go, vendor/github.com/google/go-cmp/cmp/export_panic.go, vendor/github.com/google/go-cmp/cmp/export_unsafe.go, vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go, vendor/github.com/google/go-cmp/cmp/internal/value/name.go, vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go, vendor/github.com/google/go-cmp/cmp/internal/value/pointer_unsafe.go, vendor/github.com/google/go-cmp/cmp/internal/value/sort.go, vendor/github.com/google/go-cmp/cmp/internal/value/zero.go, vendor/github.com/google/go-cmp/cmp/options.go, vendor/github.com/google/go-cmp/cmp/path.go, vendor/github.com/google/go-cmp/cmp/report.go, vendor/github.com/google/go-cmp/cmp/report_compare.go, vendor/github.com/google/go-cmp/cmp/report_references.go, vendor/github.com/google/go-cmp/cmp/report_reflect.go, vendor/github.com/google/go-cmp/cmp/report_slices.go, vendor/github.com/google/go-cmp/cmp/report_text.go, vendor/modules.txt
This PR extends CCM as follows:
- Introduced a new environment variable to accept the name of the CCM worker firewall. If the flag is missing or empty, we're not going to take any of the following steps.
- Using client-go, created a controller that watches for Service changes. If a Service is created or changed and has type NodePort, we modify the specified CCM worker firewall to accept traffic for all protocols and sources on that NodePort. Conversely, if a Service changes its type to something else or gets deleted entirely, we undo the worker firewall change.
- Created a loop to periodically fetch the CCM worker firewall configuration from the API and check if there's a delta between it and the target configuration it should have based on the existing Services (which we can look up from …
=> firewalls: add controller to manage worker firewall for public access

CHANGELOG.md, cloud-controller-manager/do/cloud.go, cloud-controller-manager/do/firewall_controller.go, cloud-controller-manager/do/firewall_controller_test.go
This PR adds exponential backoff as the retry mechanism for the firewall controller. Specifically, the service informer when handling event notifications for:
- `Add` service
- `Update` service
- `Delete` service
=> firewalls: add exponential backoff to service informer

cloud-controller-manager/do/firewall_controller.go, cloud-controller-manager/do/firewall_controller_test.go
Discovered a bug where we write tags instead of addresses to the firewall inbound rules when creating the inbound rules. So allow all access to that nodeport did not work.
This PR:
- adds addresses to inbound rule sources, instead of tags
- updates the tests to check for addresses instead of tags when testing inbound rule objects
=> Add addresses instead of tags for inbound rule sources

cloud-controller-manager/do/resources.go
This mutex seems to be a leftover from a former cache implementation
that no longer exists in the code.
=> Remove unused mutex

CHANGELOG.md, cloud-controller-manager/do/cloud.go, cloud-controller-manager/do/health.go, cloud-controller-manager/do/health_test.go, go.mod, vendor/modules.txt
We use the `healthz` package from `k8s.io/apiserver` to implement our health check. However, that check does not expose the failure reason in the logs. Example output:
```
I1002 08:05:39.882128       1 healthz.go:200] [-]godo failed: reason withheld
```
As described in [an upstream code comment](https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/f3ea5608898f253f7bfd85de35f166dde36a278a/vendor/k8s.io/apiserver/pkg/server/healthz/healthz.go#L226-L227), the rationale here is that the endpoint is public and not supposed to give away sensitive data. Instead, Kubernetes users are [expected to inspect failure details through separate, authenticated access](https://stackoverflow.com/a/53861547).
This makes the package a bad fit for our use case because (1) we do not have …
=> Expose health check failures

CHANGELOG.md
Two unreleased changes were accidentally grouped under the 0.1.27 release. Move them to the "unreleased" block.
We also reorder the 0.1.27 items to match the most-recent-first order we normally use.
=> Move unreleased changes

Makefile, scripts/update-k8s.sh
The latest Kubernetes dependencies moved from using the kubernetes-X.Y.Z tag to vX.Y.Z, which our upgrade script now accounts for.
We also remove the Makefile variable indicating which Kubernetes version we are using since that information can now be easily retrieved from the `go.mod` file.
A follow-up PR will update the Kubernetes dependencies to 1.19.3.
=> Target proper tags when updating Kubernetes dependencies

CHANGELOG.md, README.md, cloud-controller-manager/do/annotations.go, cloud-controller-manager/do/firewall_controller.go, cloud-controller-manager/do/firewall_controller_test.go, cloud-controller-manager/do/loadbalancers.go
This change enables more direct control over how `NodePort` Services should be accessible through a new configuration annotation. One use case is when a `NodePort` is to be used for VPC-internal connectivity only, in which case no public access is desirable at all.
We also extract boolean annotation value parsing into a dedicated helper function and refactoring existing usages accordingly.
=> Support marking Services as firewall-unmanaged

CHANGELOG.md, cloud-controller-manager/do/cloud.go, cloud-controller-manager/do/common.go, cloud-controller-manager/do/firewall_controller.go, cloud-controller-manager/do/firewall_controller_test.go, cloud-controller-manager/do/firewall_fixture_test.go, cloud-controller-manager/do/metrics.go
This change updates our firewall-related metrics design in the following aspects:
- Rename `api_request_duration_seconds` to `api_operation_duration_seconds` and capture API operations (get by ID, get by list, create, update) instead of HTTP requests. This allows us to distinguish between requests using the same method (namely GETs by ID and by list) while also making it easier for the user to understand what these metrics are about (telling what a PUT or POST means is less clear than a "create" or "update").
- Rename `run_loop_duration_seconds` to `resource_sync_duration_seconds` to (presumably) ease understanding: the former name did not easily imply what kind of functionality happened during a run loop.
- Add a "result" label to be two before-mentioned metrics to easily parse for …
=> Improve firewall metrics design

CHANGELOG.md, cloud-controller-manager/do/firewall_controller.go
The counter metrics would never increase because we forgot to call the `Inc()` method.
=> Fix broken firewall counter metrics by incrementing

docs/controllers/services/annotations.md
HTTPS as health check protocol for LBs has been supported in quite a while but was not documented.
=> Include HTTPS in LB health check protocol docs

docs/controllers/services/annotations.md
As announced today: https://www.digitalocean.com/blog/introducing-new-digitalocean-load-balancers-plans/
=> Remove beta note from LB size annotation

docs/controllers/services/examples/README.md
This is an upstream label implemented in the CCM core part, so we automatically support it.
Fixes #375
/cc @braghettos
=> Document label to exclude specific nodes from the LB target set

.github/workflows/release.yml
The new version of gh release workflow supports tag_name and tag_committish which we use in the release workflow
=> update gh release workflow version

README.md
This is hard to maintain and unnecessary. Drop it in favor of the Github Releases page.
Additionally, update the section which says that CCM is not production-ready, which it quite is at this point.
=> Remove latest version reference in docs

.github/workflows/test.yml, Makefile
* Makefile: set SHELL to bash (default is `sh` which doesn't have the `[[` builtin)
* Makefile: add echo to compile task to confirm build succeeds
* Makefile: use go 1.17.6 to compile binary
* workflow: require image to build before merging PRs
=> Makefile: fix binary compilation

cloud-controller-manager/cmd/digitalocean-cloud-controller-manager/Dockerfile
using an old alpine version can contain several security issues and be very outdated
so bumping to the latest one available
also if use `trivy` we got
```
2022-02-12T16:28:10.982+0100    WARN    This OS version is no longer supported by the distribution: alpine 3.6.5
```
/assign @timoreimann
=> dockerfile: update alpine base image to the latest to fix any security issues

releases/dev.yml
- annotation for critical-pod is deprecated updating to priorityClassName
- add new toleration for k8s 1.24+
already tested this in https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/pull/315
cc @timoreimann
=> update ccm for deprecations and tolerations for k8s 1.24+

docs/controllers/services/README.md
UDP is now available to all users of load balancers on DOKS versions 1.21.11-do.1 or 1.22.8-do.1 and higher.
=> controllers/services/load-balancer/docs: update docs to remove the requirement for needing to contact support to enable UDP

cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go
This seems to have been left out of https://github.com/digitalocean/digitalocean-cloud-controller-manager/pull/543
=> loadbalancers: support http3 in do-loadbalancer-protocol annotation

Makefile
CI builds fail with the following error: 
```
Status: Downloaded newer image for golang:1.19
error obtaining VCS status: exit status 1[28](https://github.com/digitalocean/digitalocean-cloud-controller-manager/actions/runs/4136491568/jobs/7150424330#step:4:29)
Use -buildvcs=false to disable VCS stamping.
make: *** [Makefile:69: compile] Error 1
```
This PR adds the -buildvcs=false flag to the CCM binary build step
=> set -buildvcs=false

.github/dependabot.yml
We always update all Kubernetes dependencies atomically and manually when we work on supporting the next minor version.
=> Have dependabot ignore Kubernetes dependencies

.github/workflows/test.yml
Tests are cheaper to execute, so do them first before starting to build a container image that can take more time.
=> Run tests before image build in CI

CHANGELOG.md, cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go
[Context]
When an LB is being created by CCM, the controller waits for the operation to complete by retrying the create continuously. This leads to an error by the LB API as long as the LB is still being provisioned (with the error from the API saying something along the lines of "LB cannot be updated while create is pending"), which in turn causes CCM to back off at exponentially increasing waiting times. This has the effect that by the time the LB has actually finished provisioning, CCM is in such deep back-off that it takes an unreasonable long time for it to recognize the LB as ready. Anecdotal data indicates that we lose up to a few single-digit minutes until CCM can retrieve the LB IP address and allow the LB to be used in Kubernetes.
Kubernetes 1.28 [added …
=> Specify retry duration when DO LB is in a being created ("new" state)

Makefile, docs/getting-started.md, releases/dev.yml
This change introduces the k8s manifest changes required to deploy the LB admission webhook alongside the existing CCM deployment. Adds:
- Validation webhook definition
- Self signed issuer for signing the admission server certs
- Serving certs for the admission server
- Service fronting the CCM pod
- Additional container running the admission server within the CCM pod.
=> feat(CON-8768): add LB admission webhook manifests

README.md
As raised in issue #684, we need to bypass the master branch protection to deploy a new version of the CCM. This README change explains how to disable the branch protection temporarily for your user.
=> doc: update release process with step to bypass branch protection

cloud-controller-manager/do/lb_annotations.go, cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go
If not provided will default to `REGIONAL`. Skipping CHANGELOG until REGIONAL_NETWORK becomes available.
=> Add annotation for LB Type with support for (`REGIONAL` and `REGIONAL_NETWORK`)

CHANGELOG.md, cloud-controller-manager/do/lb_annotations.go, cloud-controller-manager/do/lb_service_admission_handler_test.go, cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go, docs/controllers/services/annotations.md
Our current health check implementation is flawed. The external load balancer should not be responsible for health checking the pods since Kubernetes is already doing that. It instead should be health checking the worker nodes themselves. This is also dependent on the externalTrafficPolicy set on the Service itself.
If the `externalTrafficPolicy=Local` then a health check node port is created to serve health checks for the node. If there are 1 or more active pods on the node, then the health check will return 200 and it will indicate how many healthy pods are running. If there is no active pods, then it will return a 503 and will fail the health checks. It is necessary for the LB to health check this dedicated endpoint to ensure we respect the lifecycle of the worker node and the pods …
=> Fix Load Balancer Health Checks

CHANGELOG.md, cloud-controller-manager/do/certificates_test.go, cloud-controller-manager/do/lb_annotations.go, cloud-controller-manager/do/lb_service_admission_handler.go, cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go, docs/controllers/services/annotations.md
This will improve the users experience when using a certificate. A name is easier to identify then a UUID. If they are using lets encrypt, the underlying UUID will change on each renewal which causes headaches for users. Certificate names are also now unique so we can identify a certificate by its name even if the underlying UUID has changed.
The existing certificate ID annotation will take precedence. If they specify a name, we will use the certificate API to look it up and get the certificate ID.
=> Add new annotation for using certificate name when configuring load balancer TLS

CHANGELOG.md, cloud-controller-manager/do/lb_annotations.go, cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go, docs/controllers/services/annotations.md, docs/getting-started.md
Additionally, do not immediately announce the overriding annotation to be removed in the future to allow for potential special cases in self-managed Kubernetes clusters.
=> Better document health check behavior

CHANGELOG.md, cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go, docs/controllers/services/annotations.md
This change introduces support for loadBalancerSourceRanges which is the preferred and recommended way to add firewall allow rules and therefore takes presedence over annotation based allow rules.
Thanks to @J0sh0nat0r for submitting the original pull request #584.
=> Add support for loadBalancerSourceRanges

cloud-controller-manager/do/lb_annotations.go, cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go, go.mod, go.sum, vendor/github.com/digitalocean/godo/apps.gen.go, vendor/github.com/digitalocean/godo/apps_accessors.go, vendor/github.com/digitalocean/godo/load_balancers.go, vendor/modules.txt
- Currently closed alpha and will document annotations when we open it up to beta
- When network=INTERNAL, the IP of the load balancer will be from the underlying VPC. This IP will only be accessible from within the VPC.
=> Add support for internal load balancers

CHANGELOG.md, cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go, go.mod, go.sum, vendor/github.com/digitalocean/godo/load_balancers.go, vendor/modules.txt
If the health check override is specified, then we will default to the setting on the LB.
=> Disable PROXY protocol for the default health check cases

CHANGELOG.md, cloud-controller-manager/do/firewall_controller.go, cloud-controller-manager/do/firewall_controller_test.go
Since NLB will route traffic over the public interface for both the LB data plane and health checks, we will need to open the appropriate health check port. This change only affects LBs who set the annotation `service.beta.kubernetes.io/do-loadbalancer-type=REGIONAL_NETWORK` and the network is `EXTERNAL` (default).
=> Add a firewall rule to open the LB health check and service port(s) when using `service.beta.kubernetes.io/do-loadbalancer-type=REGIONAL_NETWORK`

cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go
- add lb ipv6 address as ingress
- update godo version
=> LBAAS: add lb ipv6 address as ingress

cloud-controller-manager/do/common.go
while 200 LB per page is supported, it doesn't work in cases with many-node clusters, since every LB also includes the backing droplets, and if there are, say 100 droplets, that's already 200 * 100 = 20000 droplets in the response
Context: https://digitalocean.slack.com/archives/C024HPA08/p1736551003363399
=> reduce the number of LBs per page when listing all LBs

cloud-controller-manager/do/common.go
The comment became incorrect after adjusting the value in https://github.com/digitalocean/digitalocean-cloud-controller-manager/pull/795/files
=> fix comment on api results per page

cloud-controller-manager/do/resources.go, cloud-controller-manager/do/resources_test.go
Spread the sync period of the loadbalancer unevenly to prevent a spike of loadbalancer API calls at the same time. We saw an issue when multiple clusters see their maintenance window happening at the same time and the CCM component is restarted at the same time. The sync tag period will match closely for all those CCM pods and all of those clusters will make a LIST api calls relatively close to each other resulting in spikes each 15minutes. This PR attempts to mitigate this issue by adding some randomness to the sync period (5minutes) as an initial delay. Thus, the new sync period will remain 15 minutes but the subsequent sync tag will be off between 0 to 300 seconds.
=> CON-11819 spread sync of load balancers

cloud-controller-manager/do/loadbalancers.go, cloud-controller-manager/do/loadbalancers_test.go
Backfill the LB type annotation in k8s LB services object. 
Existing and new LBs will always have the two following annotations: 
```yaml
metadata:
annotations:
kubernetes.digitalocean.com/load-balancer-id: <cluster-uuid>
service.beta.kubernetes.io/do-loadbalancer-type: <type>
```
=> CON-12382 backfill lb type annotation in k8s LB service object

CHANGELOG.md, cloud-controller-manager/do/common.go, cloud-controller-manager/do/common_test.go, cloud-controller-manager/do/droplets.go, cloud-controller-manager/do/droplets_test.go, cloud-controller-manager/do/loadbalancers.go
With the upgrade from instance to instancev2 done in this [PR](https://github.com/digitalocean/digitalocean-cloud-controller-manager/pull/776), we assumed that the node is pre propulated with a `node.spec.providerID` that is not empty. This is because in DOKS, we leverage the kubeletconfiguration and specify the droplet id in it which in turns sets it on the node object when it joins the clusters. This is an issue because not all solutions using DO CCM will use this configuration. One example is Rancher and currently if you specify the External cloud provider and install the latest version of CCM from our main repository branch (https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/master/releases/digitalocean-cloud-controller-manager/v0.1.61.yml), the cluster never …
=> Fetch providerID from DigitalOcean API as a fallback if not specified on the node object
